#!/usr/bin/env bash
# pair.sh — print everything needed to pair phones/clients with the live box.
# Perch QR itself is generated by the Perch repo's pair.sh ON THE SERVER
# (it reads the server's API key); this helper gets you there.
#
# ⚠️ THE QR IS A CREDENTIAL — full agent shell. Trusted camera, trusted room.
set -euo pipefail

HOST="$(terraform -chdir=terraform output -raw server_ipv4 2>/dev/null || true)"
[[ -n "$HOST" ]] || { echo "No terraform output. Run: make apply"; exit 2; }

echo "remote-agent-kit · pair"
echo
echo "1) Make sure Tailscale is on this machine AND the phone (same tailnet)."
echo "2) SSH to the server and run the Perch pairing script there:"
echo
echo "     ssh hermes@${HOST}"
echo "     bash <(curl -fsSL https://raw.githubusercontent.com/aryaminus/perch/main/scripts/pair.sh) --tailscale"
echo
echo "   (or copy Perch's scripts/pair.sh over first if you prefer not to curl)."
echo "3) Scan the QR with Perch → 'Scan to connect'."
echo
echo "Telegram test instead:"
echo "  Open your bot in Telegram and send: hello"
echo "  Debug: ssh hermes@${HOST} 'journalctl --user -u hermes-gateway -n 100'"
