#!/usr/bin/env bash
# pair.sh — print everything needed to pair phones/clients with the live box.
# Perch QR itself is generated by the public perch-site pair.sh ON THE SERVER
# (it reads the server's API key); this helper gets you there.
#
# ⚠️ THE QR IS A CREDENTIAL — full agent shell. Trusted camera, trusted room.
set -euo pipefail

HOST="$(terraform -chdir=terraform output -raw server_ipv4 2>/dev/null || true)"
[[ -n "$HOST" ]] || { echo "No terraform output. Run: make apply"; exit 2; }

echo "remote-agent-kit · pair"
echo
echo "1) Make sure Tailscale is on this machine AND the phone (same tailnet)."
# iOS REQUIRES the https MagicDNS name (ATS refuses cleartext to 100.x);
# derive it from the local tailnet when possible.
if command -v tailscale >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1; then
  HTTPS_URL="$(RK_AGENT_HOST="$(grep -m1 agent_hostname ansible/inventory/group_vars/all.yml 2>/dev/null | awk '{print $2}' || echo agentbox)" tailscale status --json 2>/dev/null | python3 -c 'import json,os,sys
try:
  d = json.load(sys.stdin)
  suf = d.get("MagicDNSSuffix", "")
  names = [p.get("HostName", "") for p in d.get("Peer", {}).values()] + [d.get("Self", {}).get("HostName", "")]
  want = os.environ.get("RK_AGENT_HOST", "agentbox")
  host = next((n for n in names if n == want), "")
  print(f"https://{host}.{suf}" if host and suf else "")
except Exception:
  print("")' || true)"
  [[ -n "$HTTPS_URL" ]] && echo "   iPhone address (HTTPS, required by iOS): $HTTPS_URL"
fi
echo "2) SSH to the server and run the public pairing script there:"
echo
echo "     ssh $(grep -m1 ansible_user ansible/inventory/hosts.yml 2>/dev/null | awk '{print $2}' || echo agentbox)@${HOST}"
echo "     curl -fsSL https://aryaminus.github.io/perch-site/pair.sh -o pair.sh"
echo "     bash pair.sh --tailscale"
echo
echo "   (download-then-run, never piped — the same script the Perch app docs point to.)"
echo "3) Scan the QR with Perch → 'Scan to connect'."
echo
echo "Telegram test instead:"
echo "  Open your bot in Telegram and send: hello"
echo "  Debug: ssh $(grep -m1 ansible_user ansible/inventory/hosts.yml 2>/dev/null | awk '{print $2}' || echo agentbox)@${HOST} 'journalctl --user -u hermes-gateway -n 100'"
