#!/usr/bin/env bash
# pair.sh — print everything needed to pair phones/clients with the live box.
# Perch QR itself is generated by the public perch-site pair.sh ON THE SERVER
# (it reads the server's API key); this helper gets you there.
#
# ⚠️ THE QR IS A CREDENTIAL — full agent shell. Trusted camera, trusted room.
set -euo pipefail

HOST="$(terraform -chdir=terraform output -raw server_ipv4 2>/dev/null || true)"
[[ -n "$HOST" ]] || { echo "No terraform output. Run: make apply"; exit 2; }

echo "remote-agent-kit · pair"
echo
echo "1) Make sure Tailscale is on this machine AND the phone (same tailnet)."
echo "2) SSH to the server and run the public pairing script there:"
echo
echo "     ssh hermes@${HOST}"
echo "     bash <(curl -fsSL https://raw.githubusercontent.com/aryaminus/perch-site/main/pair.sh) --tailscale"
echo
echo "   (the same script the Perch app docs point to; never fetch pairing tools elsewhere)."
echo "3) Scan the QR with Perch → 'Scan to connect'."
echo
echo "Telegram test instead:"
echo "  Open your bot in Telegram and send: hello"
echo "  Debug: ssh hermes@${HOST} 'journalctl --user -u hermes-gateway -n 100'"
